clean_sampling_method <- function(x){

  case_when(
    x == "abn" ~ "animal_baited_net",
    x == "alc" ~ "other",
    x == "alc_in" ~  "other",
    x == "cdc lt" ~ "cdc_lt_unk",
    x == "cdc lt_in" ~ "cdc_lt_ind",
    x == "cdc lt_out" ~ "cdc_lt_out",
    x == "hbn" ~ "human_baited_net_unk",
    x == "hbn_in" ~ "human_baited_net_ind",
    x == "hbn_out" ~ "human_baited_net_out",
    x == "hlc" ~ "human_landing_catch_unk",
    x == "hlc_in" ~ "human_landing_catch_ind",
    x == "hlc_out" ~ "human_landing_catch_out",
    x == "hri" ~  "hri", # house resting indoors
    x == "ib" ~ "other",
    x == "larvae" ~ "larvae",
    x == "odour trap" ~  "odour",
    x == "owt" ~ "other",
    x == "ro" ~  "outdoor_resting",
    x == "ro_ani_shelter" ~  "outdoor_resting",
    x == "ro_pit" ~  "outdoor_resting",
    x == "ro_shelter" ~  "outdoor_resting",
    x == "tent trap" ~  "tent_trap",
    x == "unknown" ~  "other",
    x == "win exit" ~  "window_exit",
    is.na(x) ~ "other",
    .default = NA
  )

  # old long list if needed for older data
  # as at 20260202 data this list is tidied right down
  # x == "?" ~  "other",
  # x == "0" ~  "other",
  # x == "AB" ~ "animal_baited_net",
  # x == "abn" ~ "animal_baited_net",
  # x == "ABN" ~ "animal_baited_net",
  # x == "alc" ~ "other",
  # x == "alc_in" ~  "other",
  # x == "cdc lt" ~ "cdc_lt_unk",
  # x == "cdc lt_in" ~ "cdc_lt_ind",
  # x == "cdc lt_out" ~ "cdc_lt_out",
  # x == "cdc-lt" ~ "cdc_lt_unk",
  # x == "CDC-LT" ~ "cdc_lt_unk",
  # x == "cdc-lt - indoor" ~ "cdc_lt_ind",
  # x == "CDC-LT - indoor" ~ "cdc_lt_ind",
  # x == "CDC-LT - indoors" ~ "cdc_lt_ind",
  # x == "cdc-lt - outdoor" ~ "cdc_lt_out",
  # x == "CDC-LT - outdoor" ~ "cdc_lt_out",
  # x == "CDC-LT- indoor" ~ "cdc_lt_ind",
  # x == "CO2" ~  "other",
  # x == "col curtains" ~  "other",
  # x == "hbn" ~ "human_baited_net_unk",
  # x == "HBN" ~ "human_baited_net_unk",
  # x == "HBN - in" ~ "human_baited_net_ind",
  # x == "HBN - out" ~ "human_baited_net_out",
  # x == "hbn (in)" ~ "human_baited_net_ind",
  # x == "hbn (out)" ~ "human_baited_net_out",
  # x == "hbn_in" ~ "human_baited_net_ind",
  # x == "hbn_out" ~ "human_baited_net_out",
  # x == "hlc" ~ "human_landing_catch_unk",
  # x == "HLC" ~ "human_landing_catch_unk",
  # x == "hlc - in" ~ "human_landing_catch_ind",
  # x == "HLC - in" ~ "human_landing_catch_ind",
  # x == "hlc - out" ~ "human_landing_catch_out",
  # x == "HLC - out" ~ "human_landing_catch_out",
  # x == "hlc_in" ~ "human_landing_catch_ind",
  # x == "hlc_out" ~ "human_landing_catch_out",
  # x == "hri" ~  "hri", # house resting indoors
  # x == "HRI" ~  "hri",
  # x == "ib" ~ "other"
  # x == "ILT" ~ "cdc_lt_ind", # is this the same as a cdc light trap indoor or a different trap?
  # x == "larvae" ~ "larvae",
  # x == "Larvae" ~ "larvae",
  # x == "LT" ~ "cdc_lt_unk", # cdc or just any other light trap?
  # x == "odour trap" ~  "odour",
  # x == "odour-trap" ~  "odour",
  # x == "OLT" ~ "cdc_lt_out",# is this same as cdc outdoor or a different trap? (or different method entirely?)
  # x == "OS" ~  "other",
  # x == "OSA" ~  "other",
  # x == "OSN" ~  "other",
  # x == "OWT" ~  "other",
  # x == "owt" ~ "other",
  # x == "ro" ~  "outdoor_resting",
  # x == "RO" ~  "outdoor_resting",
  # x == "ro (ani-shelter)" ~  "outdoor_resting",
  # x == "RO (ani-shelter)" ~  "outdoor_resting",
  # x == "ro (pit)" ~  "outdoor_resting",
  # x == "ro (shelter)" ~  "outdoor_resting",
  # x == "ro_ani_shelter" ~  "outdoor_resting",
  # x == "ro_pit" ~  "outdoor_resting",
  # x == "ro_shelter" ~  "outdoor_resting",
  # x == "tent trap" ~  "tent_trap",
  # x == "unknown" ~  "other",
  # x == "win exit" ~  "window_exit",
  # x == "winexit" ~  "window_exit",
  # x == "WinExit" ~  "window_exit",
  # is.na(x) ~ "other",


  # aim for hlc_in, hlc_out,  only use HLC as count data
  # find effort measures biting_number_of_sampling_nights_indoors


  # current 20250707

  # "?",
  # "0",
  # "AB",
  # "abn",
  # "ABN",
  # "alc",
  # "alc_in",
  # "cdc lt",
  # "cdc lt_in",
  # "cdc lt_out",
  # "cdc-lt",
  # "CDC-LT",
  # "cdc-lt - indoor",
  # "CDC-LT - indoor",
  # "CDC-LT - indoors",
  # "cdc-lt - outdoor",
  # "CDC-LT - outdoor",
  # "CDC-LT- indoor",
  # "CO2",
  # "col curtains",
  # "hbn",
  # "HBN",
  # "HBN - in",
  # "HBN - out",
  # "hbn (in)",
  # "hbn (out)",
  # "hbn_in",
  # "hbn_out",
  # "hlc",
  # "HLC",
  # "hlc - in",
  # "HLC - in",
  # "hlc - out",
  # "HLC - out",
  # "hlc_in",
  # "hlc_out",
  # "hri",
  # "HRI",
  # "ILT",
  # "larvae",
  # "Larvae",
  # "LT",
  # "odour trap",
  # "odour-trap",
  # "OLT",
  # "OS",
  # "OSA",
  # "OSN",
  # "OWT",
  # "ro",
  # "RO",
  # "ro (ani-shelter)",
  # "RO (ani-shelter)",
  # "ro (pit)",
  # "ro (shelter)",
  # "ro_ani_shelter",
  # "ro_pit",
  # "ro_shelter",
  # "tent trap",
  # "unknown",
  # "win exit",
  # "winexit",
  # "WinExit",
  # NA

}
