target_spp_test_only <- function(){

  # latest 20241108

  c(
    # "abscurus",
    "arabiensis",
    # "ardensis",
    # "barberellus",
    # "brohieri",
    # "brucei",
    # "brunnipes",
    # "bwambae",
    # "caliginosus",
    # "carnevalei",
    # "christyi",
    # "cinctus",
    # "cinereus",
    # "claviger",
    "coluzzii",
#    "coustani",
    # "coustani_complex",
    # "cristipalpis",
    # "cydippis",
    # "dattali",
    # "demeilloni",
    # "distinctus",
    # "domicola",
    # "dthali",
    # "flavicosta",
    # "fontenillei",
    # "freetownensis",
    "funestus",
#    "funestus_complex",
    # "funestus-like",
    # "gabonensis",
    "gambiae"#,
#    "gambiae_coluzzii",
#    "gambiae_complex",
    # "garnhami",
    # "gibbinsi",
    # "hancocki",
    # "harperi",
    # "implexus",
    # "kingi",
    # "labranchiae",
    # "leesoni",
    # "letabensis",
    # "listeri",
    # "longipalpis",
    # "maculipalpis",
    # "marshallii",
    # "marshallii_complex",
    # "mascarensis",
#    "melas",
#    "merus",
#    "moucheti",
    # "multicolor",
    # "namibiensis",
    # "natalensis",
#    "nili",
    # "nili_complex",
    # "obscurus",
    # "ovengensis",
    # "paludis",
    # "parensis",
    # "pauliani",
#    "pharoensis"#,
    # "pretoriensis",
    # "pseudopunctipennis",
    # "quadriannulatus",
    # "quadriannulatus sp. B",
    # "quadrimaculatus",
    # "radama",
    # "rhodesiensis",
    # "rivulorum",
    # "rivulorum-like",
#    "rufipes",
    # "rupicolus",
    # "salbaii",
    # "sergentii",
    # "smithii",
#    "squamosus",
    # "stephensi",
    # "swahilicus",
    # "tenebrosus",
    # "theileri",
    # "vaneedeni",
    # "vinckei",
    # "wellcomei",
    # "wilsoni",
#    "ziemanni"
  )


}
