target_spp <- function(){

  # latest 20241108

  c(
    # "abscurus",
    "arabiensis", # in sinka 2010
    # "ardensis",
    # "barberellus",
    # "brohieri",
    # "brucei",
    # "brunnipes",
    # "bwambae",
    # "caliginosus",
    # "carnevalei",
    # "christyi",
    # "cinctus",
    # "cinereus",
    # "claviger",
    "coluzzii",
    "coustani",
    # "coustani_complex",
    # "cristipalpis",
    # "cydippis",
    # "dattali",
    # "demeilloni",
    # "distinctus",
    # "domicola",
    # "dthali",
    # "flavicosta",
    # "fontenillei",
    # "freetownensis",
    "funestus", # in sinka 2010
    ##"funestus_complex",
    # "funestus-like",
    # "gabonensis",
    "gambiae",  # in sinka 2010
    ##"gambiae_coluzzii",
    ##"gambiae_complex",
    # "garnhami",
    # "gibbinsi",
    # "hancocki",
    # "harperi",
    # "implexus",
    # "kingi",
    # "labranchiae",
    # "leesoni",
    # "letabensis",
    # "listeri",
    # "longipalpis",
    "maculipalpis",
    # "marshallii",
    # "marshallii_complex",
    # "mascarensis",
    "melas", # in sinka 2010
    "merus", # in sinka 2010
    "moucheti", # in sinka 2010
    # "multicolor",
    # "namibiensis",
    # "natalensis",
    "nili",  # in sinka 2010
    # "nili_complex",
    # "obscurus",
    # "ovengensis",
    # "paludis",
    # "parensis",
    # "pauliani",
    "pharoensis",
    # "pretoriensis",
    # "pseudopunctipennis",
    "quadriannulatus",
    # "quadriannulatus sp. B",
    # "quadrimaculatus",
    # "radama",
    # "rhodesiensis",
    # "rivulorum",
    # "rivulorum-like",
    "rufipes",
    # "rupicolus",
    # "salbaii",
    # "sergentii",
    # "smithii",
    "squamosus",
    # "stephensi",
    # "swahilicus",
    # "tenebrosus",
    # "theileri",
    # "vaneedeni",
    # "vinckei",
    # "wellcomei",
    # "wilsoni",
    "ziemanni"
  )


}
