# Regenerate extras/mu_hfp_manifest.md.
#
# Provenance record for the Mu et al. (2022) Human Footprint download: one row
# per year, plus the native-grid verification. Lives in extras/ rather than R/
# so tar_source() does not pick it up -- this is a document generator, not
# pipeline machinery. Run it from the project root after `mu_hfp_year` has
# been built. Run from the project root.

suppressMessages({
  library(terra)
  library(targets)
})

source("R/mu_hfp_figshare_manifest.R")
source("R/stack_mu_hfp.R")

outputdir <- "outputs/raster/mu_hfp"
outfile <- "extras/mu_hfp_manifest.md"

man <- mu_hfp_figshare_manifest()

man$output <- file.path(outputdir, sprintf("mu_hfp_%d.tif", man$year))
man$present <- file.exists(man$output)
man$output_bytes <- ifelse(man$present, file.size(man$output), NA_real_)
man$retrieved <- ifelse(
  man$present,
  format(as.Date(file.mtime(man$output)), "%Y-%m-%d"),
  NA_character_
)

rows <- sprintf(
  "| %d | %s | %s | `%s` | %s | %s | %s |",
  man$year,
  man$name,
  formatC(man$size_bytes, format = "d", big.mark = ","),
  man$supplied_md5,
  man$download_url,
  man$version,
  ifelse(is.na(man$retrieved), "not retrieved", man$retrieved)
)

series <- file.path(outputdir, "mu_hfp_all.tif")

series_note <- if (file.exists(series)) {
  r <- terra::rast(series)
  yrs <- hfp_layer_years(r)
  mm <- terra::global(r, fun = c("min", "max"), na.rm = TRUE)
  tags <- terra::metags(r)
  divisor <- tags$value[tags$name == "hfp_scale_divisor"]

  sprintf(
    paste0(
      "`%s` -- %d layers, %d-%d, %d x %d on `project_mask_5`, ",
      "values %.4f to %.4f, %s on disk.\n\n",
      "The whole series is divided by one constant, **%s** (the maximum over ",
      "every year and every cell), so that between-year differences are ",
      "preserved rather than being rescaled away year by year. It is stored in ",
      "the file as the `hfp_scale_divisor` metadata tag: read it back with ",
      "`terra::metags(terra::rast(\"%s\"))`."
    ),
    series, terra::nlyr(r), min(yrs), max(yrs),
    terra::nrow(r), terra::ncol(r),
    min(mm$min, na.rm = TRUE), max(mm$max, na.rm = TRUE),
    format(structure(file.size(series), class = "object_size"), units = "auto"),
    if (length(divisor)) divisor else "unknown",
    series
  )
} else {
  "`mu_hfp_all.tif` has not been built yet."
}

writeLines(
  c(
    "# Mu et al. (2022) Human Footprint — download manifest",
    "",
    "Generated by `extras/mu_hfp_write_manifest.R`. Source documentation and the",
    "projection details are in `data/raw/mu_hfp/README.md`.",
    "",
    "## Source",
    "",
    "> Mu, H., Li, X., Wen, Y., Huang, J., Du, P., Su, W., Miao, S., Geng, M. (2022).",
    "> A global record of annual terrestrial Human Footprint dataset from 2000 to 2018.",
    "> *Scientific Data* **9**:176. doi:10.1038/s41597-022-01284-8",
    "",
    sprintf(
      "figshare article **%d**, version **%d**, doi:10.6084/m9.figshare.16571064. Licence CC BY 4.0.",
      man$article[1], man$version[1]
    ),
    "",
    sprintf(
      paste(
        "**%d annual files, %d-%d** — not the 2000-2018 the paper and the item",
        "description both claim. The years are enumerated from the figshare API",
        "by `mu_hfp_figshare_manifest()`; nothing hardcodes a range."
      ),
      nrow(man), min(man$year), max(man$year)
    ),
    "",
    sprintf(
      "Total download %s across %d files.",
      format(
        structure(sum(man$size_bytes), class = "object_size"),
        units = "auto"
      ),
      nrow(man)
    ),
    "",
    "## Files",
    "",
    "`bytes` and `md5` are the zip as served by figshare. Every download was",
    "checked against `supplied_md5` before it was opened; a mismatch deletes the",
    "file and errors, so a row here means the checksum matched. The zips and the",
    "global GeoTIFFs were deleted after reprojection — see the README for why.",
    "",
    "| year | file | bytes | md5 | source URL | article version | retrieved |",
    "|---|---|---:|---|---|---:|---|",
    rows,
    "",
    "## Native grid, as downloaded",
    "",
    "Checked on the source GeoTIFFs before reprojection, for the earliest and",
    "latest years:",
    "",
    "| | hfp2000.tif | hfp2024.tif |",
    "|---|---|---|",
    "| CRS | World_Mollweide | World_Mollweide |",
    "| resolution | 1000 m x 1000 m | 1000 m x 1000 m |",
    "| dimensions | 16382 x 36081 x 1 | 16382 x 36081 x 1 |",
    "| cells | 591,078,942 | 591,078,942 |",
    "| xmin, xmax | -18040094.1, 18040905.9 | -18040094.1, 18040905.9 |",
    "| ymin, ymax | -7363042.9, 9018957.1 | -7363042.9, 9018957.1 |",
    "| data type | FLT4S | FLT4S |",
    "| minmax | 0, 50 | 0, 50 |",
    "| NA cells | 456,924,636 (77.3%) | 456,924,636 (77.3%) |",
    "",
    "`terra::compareGeom(hfp2000, hfp2024)` is `TRUE`, and extent, resolution,",
    "dimensions and NA count are identical, so the series shares one grid. The",
    "CRS is Mollweide and the resolution is 1000 m, as the paper states.",
    "",
    "The only difference between the two eras is internal TIFF compression:",
    "2000-2018 members inflate to 2255.0 MB each and 2019-2024 to 546.2 MB, which",
    "is why the zips differ in size. The grids do not differ.",
    "",
    "## Derived series",
    "",
    series_note,
    ""
  ),
  outfile
)

cat("wrote", outfile, "\n")
